version: '3'
services:
    nginx:
        container_name: nginx
        image: jwilder/nginx-proxy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs/nginx/:/etc/nginx/certs/:ro
            - ./keyserver.nginx.conf:/etc/nginx/vhost.d/keyserver.rde.filesenderbeta.surf.nl:ro
            - ./proxyserver.nginx.conf:/etc/nginx/vhost.d/proxy.rde.filesenderbeta.surf.nl:ro
            - ./rde-keyserver/media/:/keyserver/media/
            - ./rde-keyserver/static/:/keyserver/static/:ro
        environment:
            ENABLE_IPV6: 'true'
            DEFAULT_HOST: keyserver.rde.filesenderbeta.surf.nl

    keyserver:
        build: ./rde-keyserver
        restart: unless-stopped
        volumes:
            - ./rde-keyserver/media/:/code/media/
            - ./rde-keyserver/static/:/code/static/
            - ./certs/saml:/code/keyserver/config/saml/
            - ./keyserver-db.sqlite3:/code/keyserver/db.sqlite3
        environment:
            VIRTUAL_HOST: keyserver.rde.filesenderbeta.surf.nl
            VIRTUAL_PROTO: uwsgi
            VIRTUAL_PORT: 8000

    proxyserver:
        build: ./rde-client-proxyserver
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: proxy.rde.filesenderbeta.surf.nl
            VIRTUAL_PORT: 5000
    demo:
        build: ./rde-demo
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: demo.rde.filesenderbeta.surf.nl
            VIRTUAL_PORT: 80
