version: '3'
services:
    nginx:
        container_name: nginx
        image: nginxproxy/nginx-proxy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs/nginx/:/etc/nginx/certs/:ro
            - ./keyserver.nginx.conf:/etc/nginx/vhost.d/keyserver.rde.filesenderbeta.surf.nl:ro
            - ./proxyserver.nginx.conf:/etc/nginx/vhost.d/proxy.rde.filesenderbeta.surf.nl:ro
            - ./keyserver-media/:/keyserver/media/
            - ./keyserver-static/:/keyserver/static/:ro
        environment:
            ENABLE_IPV6: 'true'
            DEFAULT_HOST: keyserver.rde.filesenderbeta.surf.nl

    keyserver:
        build: ./rde-keyserver
        restart: unless-stopped
        volumes:
            - ./keyserver-media/:/code/media/
            - ./keyserver-static/:/code/static/
            - ./certs/saml:/code/keyserver/config/saml/
            - ./keyserver-db.sqlite3:/code/keyserver/db.sqlite3
        environment:
            VIRTUAL_HOST: keyserver.rde.filesenderbeta.surf.nl
            VIRTUAL_PROTO: uwsgi
            VIRTUAL_PORT: 8000
            DJANGO_SECRET_KEY: 'django-insecure-nta2^r4xet@@6r#*ue*%a8(4v2&_2%&6%xe1euxm_(lx1#zay^'
            DJANGO_ALLOWED_HOSTS: keyserver.rde.filesenderbeta.surf.nl
            DJANGO_DEBUG: 'False'
            DJANGO_BASE_URL: https://keyserver.rde.filesenderbeta.surf.nl
            DJANGO_SAML_IDP_METADATA_URL: https://metadata.test.surfconext.nl/idp-metadata.xml

    proxyserver:
        build: ./rde-client-proxyserver
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: proxy.rde.filesenderbeta.surf.nl
            VIRTUAL_PORT: 5000

    demo:
        build: ./rde-demo
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: demo.rde.filesenderbeta.surf.nl
            VIRTUAL_PORT: 80
            KEYSERVER_URL: https://keyserver.rde.filesenderbeta.surf.nl
            PROXYSERVER_URL: https://proxy.rde.filesenderbeta.surf.nl
            PROXYSERVER_WS_URL: wss://proxy.rde.filesenderbeta.surf.nl

